/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.TelaDiretrizes;
/**
 *
 * @author 824110512
 */
public class TelaTermos extends javax.swing.JFrame {

    /**
     * Creates new form DiretrizesTela
     */
    public TelaTermos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoreject = new javax.swing.JButton();
        botaoaccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoreject.setText("Rejeitar");
        botaoreject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaorejectActionPerformed(evt);
            }
        });

        botaoaccept.setText("Concordar \ne continuar");
        botaoaccept.setLabel(("<html>Linha de cima<br>Linha de baixo</html>"););
        botaoaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoacceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(botaoreject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoaccept, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoreject)
                    .addComponent(botaoaccept))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaorejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaorejectActionPerformed
        // TODO add your handling code here:
       //TelaLogin login = new TelaLogin();
       //login.setVisible(true);
    }//GEN-LAST:event_botaorejectActionPerformed

    private void botaoacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoacceptActionPerformed
        // TODO add your handling code here:
       // TelaPoliticas politicas = new TelaPoliticas();
        //politicas.setVisible(true);
    }//GEN-LAST:event_botaoacceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTermos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoaccept;
    private javax.swing.JButton botaoreject;
    // End of variables declaration//GEN-END:variables
}
